environment:
  nodejs_version: "0.12"
init:
  - git config --global core.autocrlf true
install:
  - ps: Install-Product node $env:nodejs_version
  - cd src\CustomSeed.Web && npm install && cd ..
branches:
  only:
    - dev
build_script:
  - build.cmd verify
clone_depth: 1
test: off
deploy: off
